### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by SeekPoint** [davidsbatista/Snowball#3]
ub16hp@UB16HP:~/ub16_prj/Snowball$ python Snowball.py parameters.cfg sentences.txt ../BREDS/seeds_positive.txt ../BREDS/seeds_negative.txt 0.7 0.7
Traceback (most recent call last):
  File "Snowball.py", line 320, in <module>
    main()
  File "Snowball.py", line 311, in main
    snowball = Snowball(configuration, seeds_file, negative_seeds, sentences_file, float(similarity), float(confidance))
  File "Snowball.py", line 31, in __init__
    self.config = Config(config_file, seeds_file, negative_seeds, sentences_file, similarity, confidance)
TypeError: 'module' object is not callable
ub16hp@UB16HP:~/ub16_prj/Snowball$

**Comment by SeekPoint** [comment]
what？

**Comment by davidsbatista** [comment]
What is the issue? I don' understand your message, can you please explain properly what is the issue you are having?

**Comment by SeekPoint** [comment]
your code has bug:
TypeError: 'module' object is not callable
