### ISSUE TITLE
I cannot find SentenceBreds.Is it a file or a package?

### ISSUE THREAD

**Issue by CarolinGao** [davidsbatista/Snowball#4]

**Comment by davidsbatista** [comment]
where did you find that error?

**Comment by cabraham96** [comment]
Hi, I am experiencing the same error. I found it in ReVerb.py

**Comment by saccitgupta** [comment]
Hi, I am experience the same error as well. Found it in ReVerb.py

**Comment by davidsbatista** [comment]
it's fixed now.
