### ISSUE TITLE
No iter found

### ISSUE THREAD

**Issue by blackxer** [davidsbatista/Snowball#9]
there is a bug in "Snowball.py"
```
File "Snowball.py", line 193, in init_bootstrapp
    if iter > 0:
TypeError: '>' not supported between instances of 'builtin_function_or_method' and 'int'
```
I cannot find "iter" variable

**Comment by davidsbatista** [comment]
can you past the command line you used?

**Comment by davidsbatista** [comment]
I'm currently doing a big refactoring - this code was not even running on Python 3 - I hope in a few days it's fixed
